### ISSUE TITLE
Doesn't respect port setting, fails to start

### ISSUE THREAD

**Issue by scottjl** [kesslern/gluecan#1]
Changed port in gluecan-config.yml. startup errors out. Doesn't matter what port I specify, it says they are all 'in use' (they aren't) and fails:

```
$ cat gluecan-config.yml
port: 17081

# No password required to add/delete if public
public: false

# Password for administration UI if not public
adminPass: password

# Database name/path
database: gluecan.sqlite

# Optional keystore for HTTPS
keystore:
  path: ~
  password: ~

$ bin/gluecan
[main] INFO org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 5.2.4 by Boxfuse
[main] INFO org.flywaydb.core.internal.database.DatabaseFactory - Database: jdbc:sqlite:gluecan.sqlite (SQLite 3.28)
[main] INFO org.flywaydb.core.internal.command.DbValidate - Successfully validated 1 migration (execution time 00:00.017s)
[main] INFO org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory - Creating Schema History table: "main"."flyway_schema_history"
[main] INFO org.flywaydb.core.internal.command.DbMigrate - Current version of schema "main": << Empty Schema >>
[main] INFO org.flywaydb.core.internal.command.DbMigrate - Migrating schema "main" to version 1 - Pastes
[main] INFO org.flywaydb.core.internal.command.DbMigrate - Successfully applied 1 migration to schema "main" (execution time 00:00.072s)
[main] INFO org.eclipse.jetty.util.log - Logging initialized @637ms to org.eclipse.jetty.util.log.Slf4jLog
[main] INFO io.javalin.Javalin - Static file handler added with path=/frontend and location=CLASSPATH. Absolute path: 'jar:file:/tmp/gluecan/lib/gluecan-frontend.jar!/frontend'.
[main] INFO io.javalin.Javalin -
           __                      __ _
          / /____ _ _   __ ____ _ / /(_)____
     __  / // __ `/| | / // __ `// // // __ \
    / /_/ // /_/ / | |/ // /_/ // // // / / /
    \____/ \__,_/  |___/ \__,_//_//_//_/ /_/

        https://javalin.io/documentation

[main] INFO io.javalin.Javalin - Starting Javalin ...
[main] INFO org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10
[main] ERROR io.javalin.Javalin - Failed to start Javalin
Exception in thread "main" java.lang.RuntimeException: Port already in use. Make sure no other process is using port 17081 and try again.
	at io.javalin.Javalin.start(Javalin.java:158)
	at io.javalin.Javalin.start(Javalin.java:127)
	at us.kesslern.MainKt.main(main.kt:19)
	at us.kesslern.MainKt.main(main.kt)
Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8080
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:308)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:396)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at io.javalin.core.JavalinServer.start(JavalinServer.kt:67)
	at io.javalin.Javalin.start(Javalin.java:148)
	... 3 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
	... 11 more
```

**Comment by kesslern** [comment]
Fixed and v1.0.1 released, thanks for the report.
